# Generated by Django 3.2.2 on 2021-05-15 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='games_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='games_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
